import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

export const dynamic = 'force-dynamic'

// ─── GET /api/ombudsman ───────────────────────────────────────────────────────

export async function GET(req: Request) {
  const supabase = await createClient()
  const url = new URL(req.url)
  const status = url.searchParams.get('status')
  const category = url.searchParams.get('category')
  const limit = Math.min(parseInt(url.searchParams.get('limit') ?? '20', 10), 50)
  const offset = parseInt(url.searchParams.get('offset') ?? '0', 10)

  let query = supabase
    .from('ombudsman_cases')
    .select(
      `id, case_number, category, title, status, support_count, created_at, resolved_at,
       complainant_id,
       complainant:profiles!ombudsman_cases_complainant_id_fkey(id, username, display_name, avatar_url, role),
       topic:topics(id, statement)`
    )
    .order('created_at', { ascending: false })
    .range(offset, offset + limit - 1)

  if (status) query = query.eq('status', status)
  if (category) query = query.eq('category', category)

  const { data, error } = await query

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  // Check which cases the current user supports
  const {
    data: { user },
  } = await supabase.auth.getUser()

  let supportedIds = new Set<string>()
  if (user && data && data.length > 0) {
    const caseIds = data.map((c: { id: string }) => c.id)
    const { data: supports } = await supabase
      .from('ombudsman_case_support')
      .select('case_id')
      .eq('user_id', user.id)
      .in('case_id', caseIds)
    supportedIds = new Set((supports ?? []).map((s: { case_id: string }) => s.case_id))
  }

  const cases = (data ?? []).map((c: Record<string, unknown>) => ({
    ...c,
    supported: supportedIds.has(c.id as string),
  }))

  return NextResponse.json({ cases, hasMore: (data?.length ?? 0) === limit })
}

// ─── POST /api/ombudsman ──────────────────────────────────────────────────────

export async function POST(req: Request) {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const body = await req.json()
  const { category, title, description, topic_id, respondent_type } = body

  if (!category || !title || !description) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
  }

  // case_number is auto-generated by a DB trigger (BEFORE INSERT)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const payload: any = {
    category,
    title: title.trim().slice(0, 200),
    description: description.trim().slice(0, 3000),
    complainant_id: user.id,
    topic_id: topic_id || null,
    respondent_type: respondent_type || null,
  }

  const { data, error } = await supabase
    .from('ombudsman_cases')
    .insert(payload)
    .select('id, case_number, category, title, status, support_count, created_at')
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json({ case: data }, { status: 201 })
}
