'use client'

/**
 * StanceShareButton
 *
 * Appears after a user has cast their vote on a topic. Lets them share
 * a branded "I voted FOR/AGAINST" card via native share, copy-to-clipboard,
 * or X (formerly Twitter).
 *
 * The shared URL points to the topic page; the OG image preview is
 * generated by /api/og/stance and baked into the meta tags of a dedicated
 * share URL rendered by the server. For now we share the topic URL directly —
 * the server-side topic page already sets its own og:image.
 *
 * For social cards we embed the stance info in the share text so it always
 * surfaces clearly in tweet previews.
 */

import { useCallback, useEffect, useRef, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Check, Copy, Share2, X } from 'lucide-react'
import { cn } from '@/lib/utils/cn'
import type { VoteSide } from '@/lib/supabase/types'

interface StanceShareButtonProps {
  topicId: string
  statement: string
  /** The side the current user voted */
  votedSide: VoteSide
  /** Topic's current FOR percentage (0–100) */
  forPct: number
  totalVotes: number
  category?: string | null
  /** Compact mode — shows only icon, no label */
  compact?: boolean
  className?: string
}

export function StanceShareButton({
  topicId,
  statement,
  votedSide,
  forPct,
  totalVotes,
  category,
  compact = false,
  className,
}: StanceShareButtonProps) {
  const [copied, setCopied] = useState(false)
  const [open, setOpen] = useState(false)
  const panelRef = useRef<HTMLDivElement>(null)
  const copyTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  const isFor = votedSide === 'blue'
  const side = isFor ? 'for' : 'against'

  // Build the shareable topic URL
  const topicUrl =
    typeof window !== 'undefined'
      ? `${window.location.origin}/topic/${topicId}`
      : `/topic/${topicId}`

  // Short statement for tweet preview
  const shortStatement =
    statement.length > 90 ? `${statement.slice(0, 87)}…` : statement

  const shareText = isFor
    ? `I voted FOR: "${shortStatement}" on Lobby Market — join the debate`
    : `I voted AGAINST: "${shortStatement}" on Lobby Market — join the debate`

  // Close panel on outside click
  useEffect(() => {
    if (!open) return
    function handle(e: MouseEvent) {
      if (panelRef.current && !panelRef.current.contains(e.target as Node)) {
        setOpen(false)
      }
    }
    document.addEventListener('mousedown', handle)
    return () => document.removeEventListener('mousedown', handle)
  }, [open])

  // Keyboard: Escape closes
  useEffect(() => {
    if (!open) return
    function handle(e: KeyboardEvent) {
      if (e.key === 'Escape') setOpen(false)
    }
    document.addEventListener('keydown', handle)
    return () => document.removeEventListener('keydown', handle)
  }, [open])

  const handleTrigger = useCallback(async () => {
    // Use native Web Share API when available (mobile devices)
    if (typeof navigator !== 'undefined' && navigator.share) {
      try {
        await navigator.share({ title: shareText, url: topicUrl })
        return
      } catch {
        // User cancelled or API unavailable — fall through to panel
      }
    }
    setOpen((v) => !v)
  }, [shareText, topicUrl])

  const handleCopy = useCallback(async () => {
    const text = `${shareText}\n${topicUrl}`
    try {
      await navigator.clipboard.writeText(text)
    } catch {
      // Fallback for environments without clipboard API
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.cssText = 'position:fixed;opacity:0'
      document.body.appendChild(ta)
      ta.select()
      document.execCommand('copy')
      document.body.removeChild(ta)
    }
    setCopied(true)
    if (copyTimer.current) clearTimeout(copyTimer.current)
    copyTimer.current = setTimeout(() => setCopied(false), 2000)
  }, [shareText, topicUrl])

  const handleTweet = useCallback(() => {
    const encoded = encodeURIComponent(`${shareText}\n\n${topicUrl}`)
    window.open(
      `https://x.com/intent/tweet?text=${encoded}`,
      '_blank',
      'noopener,noreferrer'
    )
    setOpen(false)
  }, [shareText, topicUrl])

  void category
  void side
  void forPct
  void totalVotes

  return (
    <div ref={panelRef} className={cn('relative', className)}>
      {/* ── Trigger ───────────────────────────────────────────────── */}
      <button
        type="button"
        onClick={handleTrigger}
        aria-label={`Share your ${isFor ? 'FOR' : 'AGAINST'} stance on this topic`}
        aria-expanded={open}
        className={cn(
          'flex items-center gap-1.5 rounded-lg transition-all',
          'focus:outline-none focus-visible:ring-2',
          isFor
            ? 'focus-visible:ring-for-500/50'
            : 'focus-visible:ring-against-500/50',
          compact
            ? cn(
                'h-8 w-8 justify-center border',
                isFor
                  ? 'bg-for-600/10 border-for-600/30 text-for-400 hover:bg-for-600/20'
                  : 'bg-against-600/10 border-against-600/30 text-against-400 hover:bg-against-600/20'
              )
            : cn(
                'px-3 py-1.5 text-xs font-mono font-semibold border',
                isFor
                  ? 'bg-for-600/10 border-for-600/30 text-for-400 hover:bg-for-600/20'
                  : 'bg-against-600/10 border-against-600/30 text-against-400 hover:bg-against-600/20'
              )
        )}
      >
        <Share2 className={cn('flex-shrink-0', compact ? 'h-3.5 w-3.5' : 'h-3 w-3')} aria-hidden="true" />
        {!compact && <span>Share stance</span>}
      </button>

      {/* ── Dropdown panel ────────────────────────────────────────── */}
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: -4 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: -4 }}
            transition={{ duration: 0.13 }}
            role="menu"
            aria-label="Share stance options"
            className={cn(
              'absolute z-50 w-52 rounded-xl shadow-2xl overflow-hidden',
              'border border-surface-300 bg-surface-100',
              // Position: prefer above on cards that have no space below
              'bottom-full mb-2 left-0'
            )}
          >
            {/* Header */}
            <div className="flex items-center justify-between px-3 py-2 border-b border-surface-300">
              <span
                className={cn(
                  'text-[10px] font-mono font-bold uppercase tracking-widest',
                  isFor ? 'text-for-400' : 'text-against-400'
                )}
              >
                You voted {isFor ? 'FOR' : 'AGAINST'}
              </span>
              <button
                type="button"
                onClick={() => setOpen(false)}
                aria-label="Close share panel"
                className="text-surface-500 hover:text-white transition-colors"
              >
                <X className="h-3 w-3" />
              </button>
            </div>

            {/* Copy stance */}
            <button
              type="button"
              role="menuitem"
              onClick={handleCopy}
              className="w-full flex items-center gap-3 px-4 py-2.5 text-sm font-mono text-white hover:bg-surface-200 transition-colors"
            >
              {copied ? (
                <Check className="h-4 w-4 text-emerald flex-shrink-0" aria-hidden="true" />
              ) : (
                <Copy className="h-4 w-4 text-surface-500 flex-shrink-0" aria-hidden="true" />
              )}
              <span className={cn(copied && 'text-emerald')}>
                {copied ? 'Copied!' : 'Copy stance'}
              </span>
            </button>

            {/* Post on X */}
            <button
              type="button"
              role="menuitem"
              onClick={handleTweet}
              className="w-full flex items-center gap-3 px-4 py-2.5 text-sm font-mono text-white hover:bg-surface-200 transition-colors"
            >
              {/* X logo */}
              <svg
                viewBox="0 0 24 24"
                className="h-4 w-4 text-surface-500 flex-shrink-0 fill-current"
                aria-hidden="true"
              >
                <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.746l7.73-8.835L1.254 2.25H8.08l4.261 5.633 5.902-5.633zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
              </svg>
              Post on X
            </button>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
