import type { MetadataRoute } from 'next'
import { createClient } from '@/lib/supabase/server'

const BASE_URL = 'https://lobby.market'

// Static routes with their change frequency and priority
const STATIC_ROUTES: MetadataRoute.Sitemap = [
  { url: `${BASE_URL}/`, changeFrequency: 'always', priority: 1.0 },
  { url: `${BASE_URL}/hub`, changeFrequency: 'weekly', priority: 0.92 },
  { url: `${BASE_URL}/archetype`, changeFrequency: 'weekly', priority: 0.88 },
  { url: `${BASE_URL}/quiz`, changeFrequency: 'daily', priority: 0.88 },
  { url: `${BASE_URL}/duel`, changeFrequency: 'always', priority: 0.82 },
  { url: `${BASE_URL}/clash`, changeFrequency: 'always', priority: 0.86 },
  { url: `${BASE_URL}/argument-battle`, changeFrequency: 'daily', priority: 0.85 },
  { url: `${BASE_URL}/anthology`, changeFrequency: 'daily', priority: 0.82 },
  { url: `${BASE_URL}/trending`, changeFrequency: 'hourly', priority: 0.9 },
  { url: `${BASE_URL}/surge`, changeFrequency: 'hourly', priority: 0.85 },
  { url: `${BASE_URL}/frontier`, changeFrequency: 'hourly', priority: 0.84 },
  { url: `${BASE_URL}/groundswell`, changeFrequency: 'hourly', priority: 0.83 },
  { url: `${BASE_URL}/velocity`, changeFrequency: 'hourly', priority: 0.82 },
  { url: `${BASE_URL}/flux`, changeFrequency: 'always', priority: 0.84 },
  { url: `${BASE_URL}/annual`, changeFrequency: 'daily', priority: 0.80 },
  { url: `${BASE_URL}/tipping-point`, changeFrequency: 'hourly', priority: 0.83 },
  { url: `${BASE_URL}/convergence`, changeFrequency: 'hourly', priority: 0.82 },
  { url: `${BASE_URL}/hotspot`, changeFrequency: 'always', priority: 0.88 },
  { url: `${BASE_URL}/split`, changeFrequency: 'hourly', priority: 0.85 },
  { url: `${BASE_URL}/momentum`, changeFrequency: 'always', priority: 0.85 },
  { url: `${BASE_URL}/temperature`, changeFrequency: 'always', priority: 0.85 },
  { url: `${BASE_URL}/mood`, changeFrequency: 'always', priority: 0.84 },
  { url: `${BASE_URL}/breakthrough`, changeFrequency: 'hourly', priority: 0.84 },
  { url: `${BASE_URL}/scoreboard`, changeFrequency: 'always', priority: 0.88 },
  { url: `${BASE_URL}/law`, changeFrequency: 'daily', priority: 0.85 },
  { url: `${BASE_URL}/law/today`, changeFrequency: 'daily', priority: 0.82 },
  { url: `${BASE_URL}/law/graph`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/law/atlas`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/law/timeline`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/law/conflicts`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/law/health`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/law/search`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/law/quality`, changeFrequency: 'daily', priority: 0.70 },
  { url: `${BASE_URL}/law/ratings`, changeFrequency: 'daily', priority: 0.70 },
  { url: `${BASE_URL}/law/wiki`, changeFrequency: 'daily', priority: 0.70 },
  { url: `${BASE_URL}/law/categories`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/law/explore`, changeFrequency: 'hourly', priority: 0.72 },
  { url: `${BASE_URL}/law/monthly`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/law/verdicts`, changeFrequency: 'hourly', priority: 0.70 },
  { url: `${BASE_URL}/law/endorsements`, changeFrequency: 'hourly', priority: 0.70 },
  { url: `${BASE_URL}/law/reviews`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/law/compare`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/law/challenges`, changeFrequency: 'daily', priority: 0.70 },
  { url: `${BASE_URL}/debate`, changeFrequency: 'hourly', priority: 0.8 },
  { url: `${BASE_URL}/floor`, changeFrequency: 'always', priority: 0.75 },
  { url: `${BASE_URL}/leaderboard`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/leaderboard/today`, changeFrequency: 'always', priority: 0.8 },
  { url: `${BASE_URL}/ladder`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/podium`, changeFrequency: 'weekly', priority: 0.72 },
  { url: `${BASE_URL}/podium/champions`, changeFrequency: 'weekly', priority: 0.7 },
  { url: `${BASE_URL}/season`, changeFrequency: 'daily', priority: 0.75 },
  { url: `${BASE_URL}/seasons`, changeFrequency: 'weekly', priority: 0.7 },
  { url: `${BASE_URL}/achievements`, changeFrequency: 'weekly', priority: 0.65 },
  { url: `${BASE_URL}/stats`, changeFrequency: 'hourly', priority: 0.65 },
  { url: `${BASE_URL}/activity-calendar`, changeFrequency: 'daily', priority: 0.6 },
  { url: `${BASE_URL}/live`, changeFrequency: 'always', priority: 0.8 },
  { url: `${BASE_URL}/vote-stream`, changeFrequency: 'always', priority: 0.8 },
  { url: `${BASE_URL}/vote-map`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/pulse`, changeFrequency: 'always', priority: 0.75 },
  { url: `${BASE_URL}/arguments`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/arguments/trending`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/word-cloud`, changeFrequency: 'hourly', priority: 0.7 },
  { url: `${BASE_URL}/arguments/reactions`, changeFrequency: 'hourly', priority: 0.72 },
  { url: `${BASE_URL}/arguments/top-scored`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/arguments/champions`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/arguments/discussions`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/discussions`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/predictions`, changeFrequency: 'hourly', priority: 0.7 },
  { url: `${BASE_URL}/oracle`, changeFrequency: 'always', priority: 0.8 },
  { url: `${BASE_URL}/verdicts`, changeFrequency: 'hourly', priority: 0.8 },
  { url: `${BASE_URL}/transcripts`, changeFrequency: 'hourly', priority: 0.8 },
  { url: `${BASE_URL}/brief`, changeFrequency: 'daily', priority: 0.75 },
  { url: `${BASE_URL}/morning`, changeFrequency: 'daily', priority: 0.80 },
  { url: `${BASE_URL}/midday`, changeFrequency: 'hourly', priority: 0.80 },
  { url: `${BASE_URL}/evening`, changeFrequency: 'daily', priority: 0.80 },
  { url: `${BASE_URL}/today`, changeFrequency: 'always', priority: 0.9 },
  { url: `${BASE_URL}/newspaper`, changeFrequency: 'daily', priority: 0.85 },
  { url: `${BASE_URL}/digest`, changeFrequency: 'weekly', priority: 0.65 },
  { url: `${BASE_URL}/topics`, changeFrequency: 'daily', priority: 0.82 },
  { url: `${BASE_URL}/topics/underrated`, changeFrequency: 'daily', priority: 0.78 },
  { url: `${BASE_URL}/topic/categories`, changeFrequency: 'weekly', priority: 0.7 },
  { url: `${BASE_URL}/issues`, changeFrequency: 'hourly', priority: 0.82 },
  { url: `${BASE_URL}/topic/graph`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/nexus`, changeFrequency: 'daily', priority: 0.70 },
  // Individual category pages
  ...(
    [
      'economics', 'politics', 'technology', 'science',
      'ethics', 'philosophy', 'culture', 'health', 'environment', 'education',
    ].map((slug) => ({
      url: `${BASE_URL}/topic/categories/${slug}`,
      changeFrequency: 'daily' as const,
      priority: 0.65,
    }))
  ),
  { url: `${BASE_URL}/consensus`,   changeFrequency: 'always', priority: 0.8 },
  { url: `${BASE_URL}/converging`,  changeFrequency: 'hourly', priority: 0.82 },
  { url: `${BASE_URL}/mandate`,     changeFrequency: 'hourly', priority: 0.82 },
  { url: `${BASE_URL}/analytics/sentiment`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/analytics/arguments`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/analytics/topics`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/analytics/coalitions`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/analytics/votes`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/analytics/laws`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/analytics/predictions`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/analytics/reactions`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/analytics/discourse`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/analytics/growth`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/analytics/consensus-shift`, changeFrequency: 'hourly', priority: 0.7 },
  { url: `${BASE_URL}/analytics/argument-quality`, changeFrequency: 'hourly', priority: 0.7 },
  { url: `${BASE_URL}/analytics/evolution`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/analytics/debates`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/analytics/faceoffs`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/analytics/reasons`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/analytics/tags`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/analytics/calibration`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/analytics/lens`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/analytics/snapshot`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/analytics/benchmark`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/analytics/drift`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/analytics/contrarian`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/analytics/resonance`, changeFrequency: 'daily', priority: 0.70 },
  { url: `${BASE_URL}/analytics/audience`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/analytics/timing`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/analytics/influence`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/analytics/consistency`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/bias`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/analytics/clout`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/analytics/groups`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/analytics/following`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/analytics/kin`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/analytics/alignment`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/analytics/streak`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/analytics/legacy`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/analytics/territory`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/analytics/opposition`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/analytics/velocity`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/analytics/persuasion`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/leaderboard/rising`, changeFrequency: 'hourly', priority: 0.72 },
  { url: `${BASE_URL}/laws/atlas`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/calibration`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/compare`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/compare-users`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/wiki`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/topic/wiki/recent`, changeFrequency: 'hourly', priority: 0.65 },
  { url: `${BASE_URL}/law/wiki/recent`, changeFrequency: 'hourly', priority: 0.65 },
  { url: `${BASE_URL}/transparency`, changeFrequency: 'hourly', priority: 0.7 },
  { url: `${BASE_URL}/accountability`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/charter`, changeFrequency: 'weekly', priority: 0.85 },
  { url: `${BASE_URL}/oath`, changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/civic-oath`, changeFrequency: 'weekly', priority: 0.72 },
  { url: `${BASE_URL}/vitals`, changeFrequency: 'hourly', priority: 0.68 },
  { url: `${BASE_URL}/depth`, changeFrequency: 'hourly', priority: 0.7 },
  { url: `${BASE_URL}/about`, changeFrequency: 'monthly', priority: 0.6 },
  { url: `${BASE_URL}/widget`, changeFrequency: 'monthly', priority: 0.6 },
  { url: `${BASE_URL}/developers`, changeFrequency: 'monthly', priority: 0.55 },
  { url: `${BASE_URL}/badges`, changeFrequency: 'monthly', priority: 0.5 },
  { url: `${BASE_URL}/help`, changeFrequency: 'monthly', priority: 0.55 },
  { url: `${BASE_URL}/glossary`, changeFrequency: 'monthly', priority: 0.65 },
  { url: `${BASE_URL}/civic-index`, changeFrequency: 'daily', priority: 0.75 },
  { url: `${BASE_URL}/civic-score`, changeFrequency: 'daily', priority: 0.75 },
  { url: `${BASE_URL}/guidelines`, changeFrequency: 'monthly', priority: 0.5 },
  { url: `${BASE_URL}/messages`, changeFrequency: 'always', priority: 0.7 },
  { url: `${BASE_URL}/senate`, changeFrequency: 'always', priority: 0.85 },
  { url: `${BASE_URL}/signals`, changeFrequency: 'always', priority: 0.85 },
  { url: `${BASE_URL}/intelligence`, changeFrequency: 'hourly', priority: 0.85 },
  { url: `${BASE_URL}/insights`, changeFrequency: 'daily', priority: 0.80 },
  { url: `${BASE_URL}/timeline`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/graveyard`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/recoil`, changeFrequency: 'daily', priority: 0.70 },
  { url: `${BASE_URL}/mindmap`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/steelman`, changeFrequency: 'daily', priority: 0.8 },
  { url: `${BASE_URL}/spar`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/activity`, changeFrequency: 'daily', priority: 0.6 },
  { url: `${BASE_URL}/activity/following`, changeFrequency: 'always', priority: 0.65 },
  { url: `${BASE_URL}/city`, changeFrequency: 'daily', priority: 0.6 },
  { url: `${BASE_URL}/coalitions`, changeFrequency: 'daily', priority: 0.6 },
  { url: `${BASE_URL}/lobby`, changeFrequency: 'daily', priority: 0.6 },
  { url: `${BASE_URL}/reactions`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/collections`, changeFrequency: 'daily', priority: 0.6 },
  { url: `${BASE_URL}/series`, changeFrequency: 'weekly', priority: 0.75 },
  { url: `${BASE_URL}/almanac`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/arcade`, changeFrequency: 'weekly', priority: 0.75 },
  { url: `${BASE_URL}/polarization`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/changelog`, changeFrequency: 'monthly', priority: 0.55 },
  { url: `${BASE_URL}/missions`, changeFrequency: 'daily', priority: 0.8 },
  { url: `${BASE_URL}/session`, changeFrequency: 'daily', priority: 0.85 },
  { url: `${BASE_URL}/session/weekly`, changeFrequency: 'weekly', priority: 0.82 },
  { url: `${BASE_URL}/wisdom`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/prompt`, changeFrequency: 'daily', priority: 0.88 },
  { url: `${BASE_URL}/prompt/archive`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/crossroads`, changeFrequency: 'weekly', priority: 0.75 },
  { url: `${BASE_URL}/crossroads/archive`, changeFrequency: 'weekly', priority: 0.65 },
  { url: `${BASE_URL}/elections`, changeFrequency: 'daily', priority: 0.8 },
  { url: `${BASE_URL}/extremes`, changeFrequency: 'hourly', priority: 0.78 },
  { url: `${BASE_URL}/flip`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/influence`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/race`, changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/battleground`, changeFrequency: 'always', priority: 0.8 },
  { url: `${BASE_URL}/collapse`, changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/mosaic`, changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/relay`, changeFrequency: 'always', priority: 0.80 },
  { url: `${BASE_URL}/relays`, changeFrequency: 'always', priority: 0.82 },
  { url: `${BASE_URL}/relays/create`, changeFrequency: 'daily', priority: 0.75 },
  { url: `${BASE_URL}/relays/today`, changeFrequency: 'always', priority: 0.84 },
  { url: `${BASE_URL}/relays/weekly`, changeFrequency: 'daily', priority: 0.82 },
  { url: `${BASE_URL}/relays/league`, changeFrequency: 'hourly', priority: 0.78 },
  { url: `${BASE_URL}/relays/showdown`, changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/relays/stats`, changeFrequency: 'hourly', priority: 0.72 },
  { url: `${BASE_URL}/relays/mine`, changeFrequency: 'daily', priority: 0.70 },
  { url: `${BASE_URL}/relays/invitations`, changeFrequency: 'always', priority: 0.65 },
  { url: `${BASE_URL}/relays/champions`, changeFrequency: 'hourly', priority: 0.72 },
  { url: `${BASE_URL}/relays/top-legs`, changeFrequency: 'hourly', priority: 0.72 },
  { url: `${BASE_URL}/relays/categories`, changeFrequency: 'daily', priority: 0.70 },
  { url: `${BASE_URL}/relays/hall-of-fame`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/relays/uncontested`, changeFrequency: 'always', priority: 0.74 },
  { url: `${BASE_URL}/position-papers`, changeFrequency: 'daily', priority: 0.76 },
  { url: `${BASE_URL}/assembly`, changeFrequency: 'always', priority: 0.82 },
  { url: `${BASE_URL}/referendum`, changeFrequency: 'always', priority: 0.82 },
  { url: `${BASE_URL}/civic-referendums`, changeFrequency: 'daily', priority: 0.80 },
  { url: `${BASE_URL}/public-record`, changeFrequency: 'daily', priority: 0.75 },
  { url: `${BASE_URL}/summit`, changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/flashpoint`, changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/hearings`, changeFrequency: 'always', priority: 0.80 },
  { url: `${BASE_URL}/tribunal`, changeFrequency: 'daily', priority: 0.75 },
  { url: `${BASE_URL}/diversity`, changeFrequency: 'weekly', priority: 0.70 },
  { url: `${BASE_URL}/bridge`, changeFrequency: 'weekly', priority: 0.70 },
  { url: `${BASE_URL}/accord`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/spectrum`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/twins`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/rivals`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/outliers`, changeFrequency: 'hourly', priority: 0.72 },
  { url: `${BASE_URL}/compass`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/lens`, changeFrequency: 'always', priority: 0.75 },
  { url: `${BASE_URL}/drift`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/shifts`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/network`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/positions`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/hot-takes`, changeFrequency: 'always', priority: 0.75 },
  { url: `${BASE_URL}/spotlight`, changeFrequency: 'daily', priority: 0.75 },
  { url: `${BASE_URL}/rising`, changeFrequency: 'daily', priority: 0.78 },
  { url: `${BASE_URL}/gems`, changeFrequency: 'hourly', priority: 0.78 },
  { url: `${BASE_URL}/amendments`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/petitions`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/civic-veto`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/pledges`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/watchdog`, changeFrequency: 'hourly', priority: 0.78 },
  { url: `${BASE_URL}/manifesto`, changeFrequency: 'monthly', priority: 0.6 },
  { url: `${BASE_URL}/capsule`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/journal`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/simulate`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/forecast`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/records`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/radar`, changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/agenda`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/dashboard`, changeFrequency: 'hourly', priority: 0.8 },
  { url: `${BASE_URL}/report-card`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/dossier`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/legacy`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/my-week`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/tally`, changeFrequency: 'hourly', priority: 0.7 },
  { url: `${BASE_URL}/verdicts`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/arcade`, changeFrequency: 'weekly', priority: 0.75 },
  { url: `${BASE_URL}/trivia`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/flashcards`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/swipe`, changeFrequency: 'daily', priority: 0.78 },
  { url: `${BASE_URL}/ballot`, changeFrequency: 'daily', priority: 0.80 },
  { url: `${BASE_URL}/reel`, changeFrequency: 'always', priority: 0.82 },
  { url: `${BASE_URL}/rapid`, changeFrequency: 'daily', priority: 0.75 },
  { url: `${BASE_URL}/crucible`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/judge`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/perspective`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/letter`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/weather`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/wrapped`, changeFrequency: 'weekly', priority: 0.7 },
  { url: `${BASE_URL}/milestones`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/skill-tree`, changeFrequency: 'weekly', priority: 0.65 },
  { url: `${BASE_URL}/streaks`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/catchup`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/coalitions/recruit`, changeFrequency: 'hourly', priority: 0.72 },
  { url: `${BASE_URL}/coalitions/standings`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/coalitions/feed`, changeFrequency: 'always', priority: 0.65 },
  { url: `${BASE_URL}/coalitions/stance-map`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/coalitions/network`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/coalitions/treaties`, changeFrequency: 'daily', priority: 0.62 },
  { url: `${BASE_URL}/leaderboard/categories`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/leaderboard/debates`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/leaderboard/laws`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/leaderboard/topics`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/leaderboard/week`, changeFrequency: 'daily', priority: 0.7 },
  { url: `${BASE_URL}/leaderboard/wiki`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/leaderboard/ambassadors`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/leaderboard/arena`, changeFrequency: 'daily', priority: 0.67 },
  { url: `${BASE_URL}/leaderboard/bounties`, changeFrequency: 'daily', priority: 0.67 },
  { url: `${BASE_URL}/leaderboard/engagement`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/leaderboard/streaks`, changeFrequency: 'hourly', priority: 0.69 },
  { url: `${BASE_URL}/leaderboard/dissent`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/leaderboard/founders`, changeFrequency: 'weekly', priority: 0.72 },
  { url: `${BASE_URL}/leaderboard/year`, changeFrequency: 'daily', priority: 0.67 },
  { url: `${BASE_URL}/leaderboard/timing`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/leaderboard/proposals`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/leaderboard/civic-score`, changeFrequency: 'hourly', priority: 0.78 },
  { url: `${BASE_URL}/predictions/leaderboard`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/stage`, changeFrequency: 'always', priority: 0.72 },
  { url: `${BASE_URL}/karma`, changeFrequency: 'daily', priority: 0.65 },
  { url: `${BASE_URL}/civic-impact`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/hotspot`, changeFrequency: 'always', priority: 0.8 },
  { url: `${BASE_URL}/forecasters`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/resolutions`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/tags`, changeFrequency: 'daily', priority: 0.72 },
  ...(
    [
      'climate', 'tax', 'housing', 'healthcare', 'education', 'immigration',
      'economy', 'democracy', 'justice', 'technology', 'privacy', 'energy',
      'welfare', 'trade', 'defense', 'policing', 'infrastructure', 'rights',
      'labor', 'environment', 'regulation', 'freedom', 'equality', 'security',
    ].map((t) => ({
      url: `${BASE_URL}/tags/${encodeURIComponent(t)}`,
      changeFrequency: 'daily' as const,
      priority: 0.65,
    }))
  ),
  { url: `${BASE_URL}/common-threads`, changeFrequency: 'hourly', priority: 0.72 },
  { url: `${BASE_URL}/feeds`, changeFrequency: 'monthly', priority: 0.55 },
  // Ch. 194–211 — live signal & analytics pages
  { url: `${BASE_URL}/undertow`, changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/standoff`, changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/pressure`, changeFrequency: 'always', priority: 0.77 },
  { url: `${BASE_URL}/barometer`, changeFrequency: 'hourly', priority: 0.76 },
  { url: `${BASE_URL}/drought`, changeFrequency: 'hourly', priority: 0.72 },
  { url: `${BASE_URL}/flash`, changeFrequency: 'always', priority: 0.80 },
  { url: `${BASE_URL}/horizon`, changeFrequency: 'hourly', priority: 0.76 },
  { url: `${BASE_URL}/meridian`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/vortex`, changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/chronicle`, changeFrequency: 'daily', priority: 0.70 },
  { url: `${BASE_URL}/magnitude`, changeFrequency: 'hourly', priority: 0.74 },
  { url: `${BASE_URL}/blindspots`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/resonance`, changeFrequency: 'daily', priority: 0.70 },
  { url: `${BASE_URL}/conviction`, changeFrequency: 'daily', priority: 0.70 },
  { url: `${BASE_URL}/rhetoric`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/timing`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/persuasion`, changeFrequency: 'daily', priority: 0.70 },
  { url: `${BASE_URL}/analytics/coverage`, changeFrequency: 'daily', priority: 0.68 },
  { url: `${BASE_URL}/awards`, changeFrequency: 'hourly', priority: 0.82 },
  { url: `${BASE_URL}/apex`, changeFrequency: 'hourly', priority: 0.80 },
  // Ch. 213–218 — newer analytical pages missing from earlier sitemap builds
  { url: `${BASE_URL}/volatility`, changeFrequency: 'hourly', priority: 0.74 },
  { url: `${BASE_URL}/zeitgeist`, changeFrequency: 'hourly', priority: 0.76 },
  { url: `${BASE_URL}/epoch`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/watershed`, changeFrequency: 'daily', priority: 0.72 },
  { url: `${BASE_URL}/frontlines`, changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/canary`, changeFrequency: 'hourly', priority: 0.74 },
  { url: `${BASE_URL}/seismic`, changeFrequency: 'hourly', priority: 0.74 },
  { url: `${BASE_URL}/tremor`, changeFrequency: 'hourly', priority: 0.74 },
  { url: `${BASE_URL}/uncertainty`, changeFrequency: 'hourly', priority: 0.74 },
  { url: `${BASE_URL}/entropy`, changeFrequency: 'hourly', priority: 0.74 },
  { url: `${BASE_URL}/amplitude`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/influx`, changeFrequency: 'hourly', priority: 0.76 },
  // Ch. 251 — The Civic Fulcrum
  { url: `${BASE_URL}/fulcrum`, changeFrequency: 'hourly', priority: 0.77 },
  // Ch. 355 — AMA Insights Archive
  { url: `${BASE_URL}/ama`, changeFrequency: 'always', priority: 0.82 },
  { url: `${BASE_URL}/ama/highlights`, changeFrequency: 'hourly', priority: 0.78 },
  { url: `${BASE_URL}/experts`, changeFrequency: 'daily', priority: 0.76 },
  { url: `${BASE_URL}/questions`, changeFrequency: 'always', priority: 0.80 },
  { url: `${BASE_URL}/questions/best`, changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/questions/unanswered`, changeFrequency: 'always', priority: 0.73 },
  { url: `${BASE_URL}/questions/leaders`, changeFrequency: 'daily', priority: 0.72 },
  // Parliamentary / Westminster institutions
  { url: `${BASE_URL}/parliament`,        changeFrequency: 'daily',  priority: 0.78 },
  { url: `${BASE_URL}/government`,        changeFrequency: 'daily',  priority: 0.78 },
  { url: `${BASE_URL}/opposition`,        changeFrequency: 'daily',  priority: 0.78 },
  { url: `${BASE_URL}/speaker`,           changeFrequency: 'weekly', priority: 0.72 },
  { url: `${BASE_URL}/shadow-cabinet`,    changeFrequency: 'daily',  priority: 0.75 },
  { url: `${BASE_URL}/order-paper`,       changeFrequency: 'daily',  priority: 0.73 },
  { url: `${BASE_URL}/committee-reports`, changeFrequency: 'weekly', priority: 0.70 },
  { url: `${BASE_URL}/oversight`,         changeFrequency: 'weekly', priority: 0.70 },
  { url: `${BASE_URL}/civic-questions`,   changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/motions`,           changeFrequency: 'hourly', priority: 0.75 },
  { url: `${BASE_URL}/grand-council`,     changeFrequency: 'daily',  priority: 0.72 },
  { url: `${BASE_URL}/lords`,             changeFrequency: 'daily',  priority: 0.76 },
  { url: `${BASE_URL}/pmqs`,              changeFrequency: 'weekly', priority: 0.70 },
  { url: `${BASE_URL}/edm`,               changeFrequency: 'daily',  priority: 0.68 },
  { url: `${BASE_URL}/hansard`,           changeFrequency: 'daily',  priority: 0.70 },
  { url: `${BASE_URL}/royal-assent`,      changeFrequency: 'daily',  priority: 0.75 },
  { url: `${BASE_URL}/confidence`,        changeFrequency: 'daily',  priority: 0.68 },
  { url: `${BASE_URL}/divisions`,         changeFrequency: 'always', priority: 0.80 },
  { url: `${BASE_URL}/supply-day`,        changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/kings-speech`,      changeFrequency: 'weekly', priority: 0.72 },
  { url: `${BASE_URL}/westminster-hall`,  changeFrequency: 'daily',  priority: 0.74 },
  // Civic Exchange — prediction market hub
  { url: `${BASE_URL}/exchange`,               changeFrequency: 'always', priority: 0.88 },
  { url: `${BASE_URL}/exchange/screener`,      changeFrequency: 'always', priority: 0.82 },
  { url: `${BASE_URL}/exchange/movers`,        changeFrequency: 'always', priority: 0.82 },
  { url: `${BASE_URL}/exchange/signals`,       changeFrequency: 'always', priority: 0.80 },
  { url: `${BASE_URL}/exchange/flow`,          changeFrequency: 'always', priority: 0.80 },
  { url: `${BASE_URL}/exchange/heatmap`,       changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/exchange/categories`,    changeFrequency: 'daily',  priority: 0.76 },
  { url: `${BASE_URL}/exchange/indices`,       changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/exchange/correlations`,  changeFrequency: 'daily',  priority: 0.74 },
  { url: `${BASE_URL}/exchange/trends`,        changeFrequency: 'always', priority: 0.78 },
  { url: `${BASE_URL}/exchange/arbitrage`,     changeFrequency: 'hourly', priority: 0.76 },
  { url: `${BASE_URL}/exchange/rotation`,      changeFrequency: 'hourly', priority: 0.74 },
  { url: `${BASE_URL}/exchange/volatility`,    changeFrequency: 'always', priority: 0.76 },
  { url: `${BASE_URL}/exchange/opportunity`,   changeFrequency: 'hourly', priority: 0.76 },
  { url: `${BASE_URL}/exchange/smart-money`,   changeFrequency: 'hourly', priority: 0.80 },
  { url: `${BASE_URL}/exchange/following`,     changeFrequency: 'always', priority: 0.80 },
  { url: `${BASE_URL}/exchange/leaderboard`,   changeFrequency: 'daily',  priority: 0.76 },
  { url: `${BASE_URL}/exchange/trades`,        changeFrequency: 'always', priority: 0.74 },
  { url: `${BASE_URL}/exchange/news`,          changeFrequency: 'always', priority: 0.76 },
  { url: `${BASE_URL}/exchange/calendar`,      changeFrequency: 'daily',  priority: 0.72 },
  { url: `${BASE_URL}/exchange/resolved`,      changeFrequency: 'daily',  priority: 0.70 },
  { url: `${BASE_URL}/exchange/wrap`,          changeFrequency: 'daily',  priority: 0.72 },
  { url: `${BASE_URL}/exchange/coalitions`,    changeFrequency: 'daily',  priority: 0.72 },
  { url: `${BASE_URL}/exchange/watchlist`,     changeFrequency: 'always', priority: 0.70 },
]

export const dynamic = 'force-dynamic'
export const revalidate = 3600 // regenerate every hour

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  try {
    const supabase = await createClient()

    const { data: topics } = await supabase
      .from('topics')
      .select('id, updated_at, status')
      .in('status', ['active', 'voting', 'law'])
      .order('updated_at', { ascending: false })
      .limit(1000)

    const topicUrls: MetadataRoute.Sitemap = (topics ?? []).flatMap((topic) => [
      { url: `${BASE_URL}/topic/${topic.id}`, lastModified: new Date(topic.updated_at), changeFrequency: (topic.status === 'law' ? 'monthly' : 'hourly') as 'monthly' | 'hourly', priority: topic.status === 'law' ? 0.7 : 0.8 },
      { url: `${BASE_URL}/topic/${topic.id}/versus`, lastModified: new Date(topic.updated_at), changeFrequency: 'daily' as const, priority: 0.55 },
      { url: `${BASE_URL}/topic/${topic.id}/evidence`, lastModified: new Date(topic.updated_at), changeFrequency: 'hourly' as const, priority: 0.6 },
      { url: `${BASE_URL}/topic/${topic.id}/synthesis`, lastModified: new Date(topic.updated_at), changeFrequency: 'daily' as const, priority: 0.55 },
      { url: `${BASE_URL}/topic/${topic.id}/themes`, lastModified: new Date(topic.updated_at), changeFrequency: 'daily' as const, priority: 0.55 },
      { url: `${BASE_URL}/topic/${topic.id}/quality`, lastModified: new Date(topic.updated_at), changeFrequency: 'daily' as const, priority: 0.5 },
      { url: `${BASE_URL}/topic/${topic.id}/connections`, lastModified: new Date(topic.updated_at), changeFrequency: 'daily' as const, priority: 0.5 },
      { url: `${BASE_URL}/topic/${topic.id}/context`, lastModified: new Date(topic.updated_at), changeFrequency: 'weekly' as const, priority: 0.5 },
      { url: `${BASE_URL}/topic/${topic.id}/predictions`, lastModified: new Date(topic.updated_at), changeFrequency: 'hourly' as const, priority: 0.6 },
      { url: `${BASE_URL}/topic/${topic.id}/impact`, lastModified: new Date(topic.updated_at), changeFrequency: 'daily' as const, priority: 0.55 },
      { url: `${BASE_URL}/topic/${topic.id}/faceoff`, lastModified: new Date(topic.updated_at), changeFrequency: 'hourly' as const, priority: 0.58 },
      { url: `${BASE_URL}/topic/${topic.id}/global`, lastModified: new Date(topic.updated_at), changeFrequency: 'daily' as const, priority: 0.55 },
    ])

    const { data: topicsWithWiki } = await supabase
      .from('topics')
      .select('id, description_updated_at, updated_at')
      .not('description', 'is', null)
      .order('description_updated_at', { ascending: false })
      .limit(500)

    const wikiUrls: MetadataRoute.Sitemap = (topicsWithWiki ?? []).map((t) => ({
      url: `${BASE_URL}/topic/wiki/${t.id}`,
      lastModified: new Date(t.description_updated_at ?? t.updated_at),
      changeFrequency: 'weekly' as const,
      priority: 0.55,
    }))

    const { data: laws } = await supabase
      .from('laws')
      .select('id, established_at')
      .order('established_at', { ascending: false })
      .limit(2000)

    const lawUrls: MetadataRoute.Sitemap = (laws ?? []).flatMap((law) => ([
      {
        url: `${BASE_URL}/law/${law.id}`,
        lastModified: new Date(law.established_at),
        changeFrequency: 'monthly' as const,
        priority: 0.75,
      },
      {
        url: `${BASE_URL}/law/${law.id}/blueprint`,
        lastModified: new Date(law.established_at),
        changeFrequency: 'weekly' as const,
        priority: 0.65,
      },
      {
        url: `${BASE_URL}/law/${law.id}/frames`,
        lastModified: new Date(law.established_at),
        changeFrequency: 'weekly' as const,
        priority: 0.65,
      },
      {
        url: `${BASE_URL}/law/${law.id}/health`,
        lastModified: new Date(law.established_at),
        changeFrequency: 'daily' as const,
        priority: 0.60,
      },
    ]))

    const { data: profiles } = await supabase
      .from('profiles')
      .select('username, updated_at')
      .not('username', 'is', null)
      .order('reputation_score', { ascending: false })
      .limit(500)

    const profileUrls: MetadataRoute.Sitemap = (profiles ?? []).flatMap((p) => ([
      { url: `${BASE_URL}/profile/${p.username}`, lastModified: new Date(p.updated_at), changeFrequency: 'weekly' as const, priority: 0.5 },
      { url: `${BASE_URL}/profile/${p.username}/achievements`, lastModified: new Date(p.updated_at), changeFrequency: 'weekly' as const, priority: 0.4 },
      { url: `${BASE_URL}/profile/${p.username}/arguments`, lastModified: new Date(p.updated_at), changeFrequency: 'daily' as const, priority: 0.45 },
      { url: `${BASE_URL}/profile/${p.username}/debates`, lastModified: new Date(p.updated_at), changeFrequency: 'weekly' as const, priority: 0.4 },
      { url: `${BASE_URL}/profile/${p.username}/impact`, lastModified: new Date(p.updated_at), changeFrequency: 'weekly' as const, priority: 0.4 },
      { url: `${BASE_URL}/profile/${p.username}/laws`, lastModified: new Date(p.updated_at), changeFrequency: 'weekly' as const, priority: 0.4 },
    ]))

    const { data: topArguments } = await supabase
      .from('topic_arguments')
      .select('id, created_at')
      .order('upvotes', { ascending: false })
      .limit(500)

    const argumentUrls: MetadataRoute.Sitemap = (topArguments ?? []).map((a) => ({
      url: `${BASE_URL}/arguments/${a.id}`,
      lastModified: new Date(a.created_at),
      changeFrequency: 'weekly' as const,
      priority: 0.45,
    }))

    const { data: tagRows } = await supabase
      .from('topics')
      .select('tags, updated_at')
      .not('tags', 'is', null)
      .order('updated_at', { ascending: false })
      .limit(500)

    const tagSet = new Map<string, Date>()
    for (const row of tagRows ?? []) {
      const rowTags: string[] = (row as { tags?: string[] }).tags ?? []
      const updatedAt = new Date((row as { updated_at: string }).updated_at)
      for (const t of rowTags) {
        const existing = tagSet.get(t)
        if (!existing || updatedAt > existing) tagSet.set(t, updatedAt)
      }
    }

    const dynamicTagUrls: MetadataRoute.Sitemap = Array.from(tagSet.entries()).map(([t, lastMod]) => ({
      url: `${BASE_URL}/tags/${encodeURIComponent(t)}`,
      lastModified: lastMod,
      changeFrequency: 'daily' as const,
      priority: 0.6,
    }))

    const { CIVIC_SERIES } = await import('@/lib/config/series')
    const seriesUrls: MetadataRoute.Sitemap = CIVIC_SERIES.map((s) => ({
      url: `${BASE_URL}/series/${s.slug}`,
      changeFrequency: 'weekly' as const,
      priority: 0.7,
    }))

    return [...STATIC_ROUTES, ...topicUrls, ...wikiUrls, ...lawUrls, ...profileUrls, ...argumentUrls, ...dynamicTagUrls, ...seriesUrls]
  } catch {
    return STATIC_ROUTES
  }
}
