import type { Metadata } from 'next'
import Link from 'next/link'
import {
  Database,
  Eye,
  Globe,
  Lock,
  Mail,
  RefreshCw,
  Shield,
  Trash2,
  UserCheck,
  Users,
} from 'lucide-react'
import { TopBar } from '@/components/layout/TopBar'
import { BottomNav } from '@/components/layout/BottomNav'
import { cn } from '@/lib/utils/cn'

export const metadata: Metadata = {
  title: 'Privacy Policy · Lobby Market',
  description:
    'How Lobby Market collects, uses, and protects your personal information. We are committed to your privacy and data security.',
  openGraph: {
    title: 'Privacy Policy · Lobby Market',
    description:
      'How we collect, use, and protect your personal information on Lobby Market.',
    type: 'website',
    siteName: 'Lobby Market',
  },
  twitter: {
    card: 'summary',
    title: 'Privacy Policy · Lobby Market',
    description: 'How Lobby Market collects, uses, and protects your personal data.',
  },
}

// ─── Types ────────────────────────────────────────────────────────────────────

interface Section {
  id: string
  icon: React.ComponentType<{ className?: string }>
  iconColor: string
  iconBg: string
  title: string
  content: React.ReactNode
}

// ─── Sections ─────────────────────────────────────────────────────────────────

const SECTIONS: Section[] = [
  {
    id: 'information-we-collect',
    icon: Database,
    iconColor: 'text-for-400',
    iconBg: 'bg-for-500/10 border-for-500/20',
    title: 'Information We Collect',
    content: (
      <div className="space-y-4 text-sm font-mono text-surface-600 leading-relaxed">
        <p>
          Lobby Market collects information you provide directly and information
          generated by your activity on the platform.
        </p>
        <div>
          <h4 className="font-semibold text-surface-400 mb-2">Account Information</h4>
          <ul className="space-y-1.5 list-none">
            {[
              'Email address (required for account creation)',
              'Username and display name (chosen by you)',
              'Password (stored as a secure hash — never in plain text)',
              'Avatar image (optional, uploaded by you)',
              'Bio and social links (optional, provided by you)',
            ].map((item) => (
              <li key={item} className="flex items-start gap-2">
                <span className="text-for-500 mt-0.5 flex-shrink-0">—</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
        <div>
          <h4 className="font-semibold text-surface-400 mb-2">Activity Data</h4>
          <ul className="space-y-1.5 list-none">
            {[
              'Votes cast on topics (which side: For or Against)',
              'Arguments, replies, and debate contributions you author',
              'Predictions you make and their outcomes',
              'Topics you subscribe to, bookmark, or react to',
              'Coalition and lobby memberships',
              'Achievements earned and civic streaks',
            ].map((item) => (
              <li key={item} className="flex items-start gap-2">
                <span className="text-for-500 mt-0.5 flex-shrink-0">—</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
        <div>
          <h4 className="font-semibold text-surface-400 mb-2">Technical Data</h4>
          <ul className="space-y-1.5 list-none">
            {[
              'IP address and general geographic region (country / region level)',
              'Browser type and device type (for responsive design)',
              'Pages viewed and time spent (anonymised analytics)',
              'Push notification subscription tokens (if you opt in)',
            ].map((item) => (
              <li key={item} className="flex items-start gap-2">
                <span className="text-for-500 mt-0.5 flex-shrink-0">—</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
        <p className="text-surface-500">
          We do not collect financial information, precise GPS location, or any
          biometric data.
        </p>
      </div>
    ),
  },
  {
    id: 'how-we-use-data',
    icon: Eye,
    iconColor: 'text-purple',
    iconBg: 'bg-purple/10 border-purple/20',
    title: 'How We Use Your Data',
    content: (
      <div className="space-y-4 text-sm font-mono text-surface-600 leading-relaxed">
        <p>
          Your data is used to operate the platform and improve your civic
          experience. We do not sell your personal information.
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {[
            { label: 'Platform operation', desc: 'Manage your account, authenticate sessions, and enforce platform rules.' },
            { label: 'Feed personalisation', desc: 'Surface topics relevant to your voting history and stated category preferences.' },
            { label: 'Analytics', desc: 'Generate your personal civic analytics (vote calibration, diversity score, etc.).' },
            { label: 'Notifications', desc: 'Send email and push notifications for debates, laws, achievements, and streaks.' },
            { label: 'Safety & moderation', desc: 'Detect and prevent spam, abuse, and coordinated inauthentic behaviour.' },
            { label: 'Product improvement', desc: 'Understand feature usage and fix bugs using aggregated, anonymised data.' },
          ].map((item) => (
            <div
              key={item.label}
              className="rounded-xl bg-surface-200/40 border border-surface-300/40 p-3.5"
            >
              <p className="font-semibold text-surface-300 text-xs mb-1">{item.label}</p>
              <p className="text-surface-500 text-xs leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </div>
    ),
  },
  {
    id: 'public-visibility',
    icon: Globe,
    iconColor: 'text-emerald',
    iconBg: 'bg-emerald/10 border-emerald/20',
    title: 'What Is Public',
    content: (
      <div className="space-y-4 text-sm font-mono text-surface-600 leading-relaxed">
        <p>
          Lobby Market is a public deliberation platform. The following information
          is visible to anyone, including non-registered visitors:
        </p>
        <div>
          <h4 className="font-semibold text-surface-400 mb-2">Always Public</h4>
          <ul className="space-y-1.5 list-none">
            {[
              'Your username and display name',
              'Arguments and debate contributions you publish',
              'Your public profile (role, clout, achievements)',
              'Coalition and lobby memberships',
              'Aggregate vote counts on topics (not individual choices)',
              'Your prediction outcomes (after resolution)',
            ].map((item) => (
              <li key={item} className="flex items-start gap-2">
                <span className="text-emerald mt-0.5 flex-shrink-0">◆</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
        <div>
          <h4 className="font-semibold text-surface-400 mb-2">Never Public</h4>
          <ul className="space-y-1.5 list-none">
            {[
              'Your email address',
              'Your individual vote on any specific topic',
              'Your direct messages',
              'Your draft arguments (saved but not submitted)',
              'Your notification preferences',
              'Your IP address or device information',
            ].map((item) => (
              <li key={item} className="flex items-start gap-2">
                <span className="text-against-400 mt-0.5 flex-shrink-0">◆</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
        <p className="text-surface-500">
          Your individual vote choice is never disclosed to other users.
          Only aggregate percentages are shown publicly.
        </p>
      </div>
    ),
  },
  {
    id: 'data-sharing',
    icon: Users,
    iconColor: 'text-gold',
    iconBg: 'bg-gold/10 border-gold/20',
    title: 'Data Sharing & Third Parties',
    content: (
      <div className="space-y-4 text-sm font-mono text-surface-600 leading-relaxed">
        <p>
          We share your data only in the limited circumstances described below.
          We never sell your data to advertisers or data brokers.
        </p>
        <div className="space-y-3">
          {[
            {
              name: 'Supabase',
              role: 'Database & authentication provider',
              desc: 'Your account data and activity are stored in Supabase (PostgreSQL). Subject to their privacy policy.',
            },
            {
              name: 'Vercel',
              role: 'Hosting & CDN',
              desc: 'The application is deployed on Vercel infrastructure. Access logs may be collected for operational purposes.',
            },
            {
              name: 'OpenAI / AI providers',
              role: 'AI features (checker, coach, simulate)',
              desc: 'When you use AI-powered features, your query text is sent to the AI provider. We do not send personal identifiers with these requests.',
            },
            {
              name: 'Legal compliance',
              role: 'Law enforcement requests',
              desc: 'We may disclose data if required by a valid legal order, court order, or government request. We will notify you where legally permitted.',
            },
          ].map((item) => (
            <div
              key={item.name}
              className="rounded-xl bg-surface-200/40 border border-surface-300/40 p-4"
            >
              <div className="flex items-center gap-2 mb-1">
                <span className="font-semibold text-surface-300 text-xs">{item.name}</span>
                <span className="text-[10px] text-surface-500 font-mono px-1.5 py-0.5 rounded bg-surface-300/30 border border-surface-400/20">
                  {item.role}
                </span>
              </div>
              <p className="text-surface-500 text-xs leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </div>
    ),
  },
  {
    id: 'data-security',
    icon: Lock,
    iconColor: 'text-against-300',
    iconBg: 'bg-against-400/10 border-against-400/20',
    title: 'Data Security',
    content: (
      <div className="space-y-4 text-sm font-mono text-surface-600 leading-relaxed">
        <p>
          We apply industry-standard security measures to protect your data. No
          system is impenetrable, but we take the following steps:
        </p>
        <ul className="space-y-2 list-none">
          {[
            'All data is encrypted in transit using TLS/HTTPS',
            'Passwords are hashed using bcrypt — we never store plaintext passwords',
            'Database access is protected by Row Level Security (RLS) policies',
            'API endpoints require authenticated sessions for private operations',
            'Push notification tokens are scoped to individual users',
            'We conduct periodic security reviews of authentication and data access patterns',
          ].map((item) => (
            <li key={item} className="flex items-start gap-2">
              <Shield className="h-3.5 w-3.5 text-against-300 flex-shrink-0 mt-0.5" />
              <span>{item}</span>
            </li>
          ))}
        </ul>
        <p className="text-surface-500">
          If you discover a security vulnerability, please report it to{' '}
          <a
            href="mailto:security@lobby.market"
            className="text-for-400 hover:underline"
          >
            security@lobby.market
          </a>{' '}
          rather than disclosing it publicly.
        </p>
      </div>
    ),
  },
  {
    id: 'your-rights',
    icon: UserCheck,
    iconColor: 'text-for-300',
    iconBg: 'bg-for-300/10 border-for-300/20',
    title: 'Your Rights & Controls',
    content: (
      <div className="space-y-4 text-sm font-mono text-surface-600 leading-relaxed">
        <p>
          You have the following rights with respect to your personal data.
          Exercise them from your Settings page or by contacting us.
        </p>
        <div className="space-y-3">
          {[
            {
              right: 'Access',
              desc: 'Request a copy of all data we hold about you. Use the Export feature in Settings → Data.',
              action: 'Settings → Data Export',
            },
            {
              right: 'Correction',
              desc: 'Update your username, display name, bio, or email at any time.',
              action: 'Settings → Profile',
            },
            {
              right: 'Deletion',
              desc: 'Request permanent deletion of your account and all associated data. Contact us at privacy@lobby.market. Published arguments may be anonymised rather than deleted.',
              action: 'Contact us',
            },
            {
              right: 'Portability',
              desc: 'Export your full civic record — votes, arguments, predictions, achievements — as structured JSON.',
              action: 'Settings → Data Export',
            },
            {
              right: 'Notification opt-out',
              desc: 'Disable email or push notifications for any event type at any time.',
              action: 'Settings → Notifications',
            },
            {
              right: 'Withdrawal of consent',
              desc: 'You may withdraw consent for data processing by deleting your account. This will stop all ongoing data collection.',
              action: 'Account deletion',
            },
          ].map((item) => (
            <div
              key={item.right}
              className="rounded-xl bg-surface-200/40 border border-surface-300/40 p-4"
            >
              <p className="font-semibold text-surface-300 text-xs mb-1">{item.right}</p>
              <p className="text-surface-500 text-xs leading-relaxed mb-2">{item.desc}</p>
              <span className="text-[10px] font-mono text-for-400 border border-for-500/30 bg-for-500/10 px-2 py-0.5 rounded">
                {item.action}
              </span>
            </div>
          ))}
        </div>
      </div>
    ),
  },
  {
    id: 'data-retention',
    icon: Trash2,
    iconColor: 'text-surface-500',
    iconBg: 'bg-surface-300/20 border-surface-400/20',
    title: 'Data Retention',
    content: (
      <div className="space-y-3 text-sm font-mono text-surface-600 leading-relaxed">
        <p>
          We retain your data for as long as your account is active or as needed
          to provide the service.
        </p>
        <ul className="space-y-1.5 list-none">
          {[
            'Account data — retained until you delete your account',
            'Vote records — retained indefinitely to maintain historical consensus integrity',
            'Published arguments — may be anonymised on deletion, not fully removed (they form part of the civic record)',
            'Direct messages — deleted when either party deletes the conversation',
            'Notification logs — retained for 90 days, then purged',
            'Analytics aggregates — retained indefinitely in anonymous form',
          ].map((item) => (
            <li key={item} className="flex items-start gap-2">
              <span className="text-surface-500 mt-0.5 flex-shrink-0">—</span>
              <span>{item}</span>
            </li>
          ))}
        </ul>
      </div>
    ),
  },
  {
    id: 'cookies',
    icon: Database,
    iconColor: 'text-gold',
    iconBg: 'bg-gold/10 border-gold/20',
    title: 'Cookies & Local Storage',
    content: (
      <div className="space-y-3 text-sm font-mono text-surface-600 leading-relaxed">
        <p>
          Lobby Market uses cookies and browser local storage for the following
          purposes:
        </p>
        <div className="space-y-2">
          {[
            {
              name: 'Authentication session cookie',
              purpose: 'Keeps you logged in across page reloads. Required for account access.',
              required: true,
            },
            {
              name: 'Notification preferences',
              purpose: 'Remembers your local notification toggle settings.',
              required: false,
            },
            {
              name: 'Feed state (local)',
              purpose: 'Stores your current scroll position and feed sort preference in localStorage.',
              required: false,
            },
            {
              name: 'Onboarding completion flag',
              purpose: 'Tracks whether you have completed the initial setup checklist.',
              required: false,
            },
          ].map((item) => (
            <div
              key={item.name}
              className="flex items-start justify-between gap-4 rounded-lg bg-surface-200/30 border border-surface-300/30 p-3"
            >
              <div>
                <p className="text-surface-300 text-xs font-semibold">{item.name}</p>
                <p className="text-surface-500 text-xs mt-0.5 leading-relaxed">{item.purpose}</p>
              </div>
              <span
                className={cn(
                  'flex-shrink-0 text-[10px] font-mono px-1.5 py-0.5 rounded border',
                  item.required
                    ? 'text-against-300 border-against-400/30 bg-against-400/10'
                    : 'text-surface-500 border-surface-400/30 bg-surface-300/20'
                )}
              >
                {item.required ? 'Required' : 'Functional'}
              </span>
            </div>
          ))}
        </div>
        <p className="text-surface-500">
          We do not use tracking cookies or share cookie data with advertising
          networks.
        </p>
      </div>
    ),
  },
  {
    id: 'changes',
    icon: RefreshCw,
    iconColor: 'text-purple',
    iconBg: 'bg-purple/10 border-purple/20',
    title: 'Changes to This Policy',
    content: (
      <div className="space-y-3 text-sm font-mono text-surface-600 leading-relaxed">
        <p>
          We may update this Privacy Policy to reflect changes in our practices
          or for legal, regulatory, or operational reasons.
        </p>
        <p>
          When we make material changes, we will notify you via email (if you
          have provided one) and via a platform notification at least 14 days
          before the change takes effect. Continued use of Lobby Market after the
          effective date constitutes acceptance of the updated policy.
        </p>
        <p>
          The current version of this policy is always available at{' '}
          <Link href="/privacy" className="text-for-400 hover:underline">
            lobby.market/privacy
          </Link>
          . The effective date is shown at the top of this page.
        </p>
      </div>
    ),
  },
  {
    id: 'contact',
    icon: Mail,
    iconColor: 'text-emerald',
    iconBg: 'bg-emerald/10 border-emerald/20',
    title: 'Contact & Data Requests',
    content: (
      <div className="space-y-3 text-sm font-mono text-surface-600 leading-relaxed">
        <p>
          For privacy-related requests, questions, or complaints, contact us at:
        </p>
        <div className="rounded-xl bg-surface-200/40 border border-surface-300/40 p-5 space-y-2">
          <div className="flex items-center gap-2">
            <Mail className="h-4 w-4 text-emerald flex-shrink-0" />
            <a
              href="mailto:privacy@lobby.market"
              className="text-for-400 hover:underline text-sm"
            >
              privacy@lobby.market
            </a>
          </div>
          <p className="text-surface-500 text-xs">
            Data access, deletion, and correction requests are processed within
            30 days.
          </p>
        </div>
        <p>
          If you are located in the European Economic Area and believe we have
          violated your data protection rights, you have the right to lodge a
          complaint with your local data protection authority.
        </p>
      </div>
    ),
  },
]

// ─── Table of contents ────────────────────────────────────────────────────────

function TableOfContents() {
  return (
    <nav className="rounded-2xl bg-surface-100 border border-surface-300 p-5 mb-8">
      <p className="text-[11px] font-mono text-surface-500 uppercase tracking-wider mb-3">
        Contents
      </p>
      <ol className="space-y-1.5">
        {SECTIONS.map((s, i) => (
          <li key={s.id}>
            <a
              href={`#${s.id}`}
              className="flex items-center gap-2 text-sm font-mono text-surface-400 hover:text-white transition-colors"
            >
              <span className="text-surface-600 tabular-nums w-4 flex-shrink-0">
                {String(i + 1).padStart(2, '0')}
              </span>
              {s.title}
            </a>
          </li>
        ))}
      </ol>
    </nav>
  )
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function PrivacyPage() {
  const effectiveDate = 'May 22, 2026'

  return (
    <div className="min-h-screen bg-surface-50">
      <TopBar />

      <main className="max-w-3xl mx-auto px-4 pt-8 pb-24 md:pb-12">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-2 mb-4">
            <Link
              href="/about"
              className="text-xs font-mono text-surface-500 hover:text-surface-400 transition-colors"
            >
              About
            </Link>
            <span className="text-surface-600">·</span>
            <span className="text-xs font-mono text-surface-400">Privacy Policy</span>
          </div>
          <div className="flex items-start gap-4 mb-4">
            <div className="flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-xl bg-for-500/10 border border-for-500/30">
              <Shield className="h-6 w-6 text-for-400" />
            </div>
            <div>
              <h1 className="font-mono text-3xl font-bold text-white leading-tight">
                Privacy Policy
              </h1>
              <p className="text-sm font-mono text-surface-500 mt-1">
                Effective date: {effectiveDate}
              </p>
            </div>
          </div>
          <div className="rounded-2xl bg-surface-100 border border-surface-300 p-5">
            <p className="text-sm font-mono text-surface-500 leading-relaxed">
              Lobby Market (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) is committed to
              protecting your privacy. This policy explains what personal data we
              collect when you use Lobby Market, how we use it, and the controls
              you have over your information.
            </p>
            <p className="text-sm font-mono text-surface-500 leading-relaxed mt-3">
              By creating an account and using Lobby Market, you agree to the
              collection and use of information in accordance with this policy.
            </p>
          </div>
        </div>

        <TableOfContents />

        {/* Sections */}
        <div className="space-y-10">
          {SECTIONS.map((section) => {
            const Icon = section.icon
            return (
              <section key={section.id} id={section.id} className="scroll-mt-20">
                <div className="flex items-center gap-3 mb-5">
                  <div
                    className={cn(
                      'flex-shrink-0 flex items-center justify-center h-10 w-10 rounded-xl border',
                      section.iconBg
                    )}
                  >
                    <Icon className={cn('h-5 w-5', section.iconColor)} />
                  </div>
                  <h2 className="font-mono text-lg font-bold text-white">
                    {section.title}
                  </h2>
                </div>
                <div className="rounded-2xl bg-surface-100 border border-surface-300 p-6">
                  {section.content}
                </div>
              </section>
            )
          })}
        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t border-surface-300">
          <div className="flex flex-wrap gap-4 text-xs font-mono text-surface-500">
            <Link href="/terms" className="hover:text-surface-400 transition-colors">
              Terms of Service
            </Link>
            <Link href="/guidelines" className="hover:text-surface-400 transition-colors">
              Community Guidelines
            </Link>
            <Link href="/about" className="hover:text-surface-400 transition-colors">
              About
            </Link>
            <Link href="/help" className="hover:text-surface-400 transition-colors">
              Help & FAQ
            </Link>
          </div>
          <p className="text-[11px] font-mono text-surface-600 mt-3">
            © 2026 Lobby Market. All rights reserved.
          </p>
        </div>
      </main>

      <BottomNav />
    </div>
  )
}
